name: eql_cmx_portal_cicd_release_pipeline_to_data_migration_env.yml
# prepare for releasing to data migration:

on:
  workflow_call :
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution'
        required: true
        type: string
      #Do Not change these values
      solution_release_folder:
       description: 'folder where the released binaries are going to be hosted *do not change*'
       type: string
       default: out/release
    secrets:
      data_migration_url:
        description: 'data_migration environment url.'
        required: true      
      data_migration_client_id:
        description: 'The data_migration client id'
        required: true
      data_migration_secrets_id:
        description: 'The secret value for authentication for data_migration'
        required: true
      data_migration_tenant_id: 
        description: 'The tenant id'
        required: true

jobs:
  data-migration:
    runs-on: windows-latest
    environment: data_migration
    env:
      RUNNER_DEBUG: 1
    steps:
    
    - name: git config to accept long paths
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git config --system core.longpaths true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.solution_name }}
        path: ${{ inputs.solution_release_folder}}
        
    - name: Import solution to data migration env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{ secrets.data_migration_url }}
        app-id: ${{ secrets.data_migration_client_id }}
        client-secret: ${{ secrets.data_migration_secrets_id }}
        tenant-id: ${{ secrets.data_migration_tenant_id }}
        solution-name: ${{ inputs.solution_name }}
        solution-file: ${{ inputs.solution_release_folder}}/${{ inputs.solution_name }}_managed.zip
        convert-to-managed: true
        force-overwrite: true
        publish-changes: true
        run-asynchronously: true
